package rssi.message;

/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'rssi.message.CommandMsg'
 * rssi.message type.
 */

public class CommandMsg extends net.tinyos.message.Message {

    /** The default size of this rssi.message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 3;

    /** The Active Message type associated with this rssi.message. */
    public static final int AM_TYPE = 3;

    /** Create a new rssi.message.CommandMsg of size 3. */
    public CommandMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new rssi.message.CommandMsg of the given data_length. */
    public CommandMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.CommandMsg with the given data_length
     * and base offset.
     */
    public CommandMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.CommandMsg using the given byte array
     * as backing store.
     */
    public CommandMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.CommandMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public CommandMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.CommandMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public CommandMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.CommandMsg embedded in the given rssi.message
     * at the given base offset.
     */
    public CommandMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.CommandMsg embedded in the given rssi.message
     * at the given base offset and length.
     */
    public CommandMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this rssi.message. Includes the
     * rssi.message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <rssi.message.CommandMsg> \n";
      try {
        s += "  [power=0x"+Long.toHexString(get_power())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [packets=0x"+Long.toHexString(get_packets())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: power
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'power' is signed (false).
     */
    public static boolean isSigned_power() {
        return false;
    }

    /**
     * Return whether the field 'power' is an array (false).
     */
    public static boolean isArray_power() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'power'
     */
    public static int offset_power() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'power'
     */
    public static int offsetBits_power() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'power'
     */
    public short get_power() {
        return (short)getUIntBEElement(offsetBits_power(), 8);
    }

    /**
     * Set the value of the field 'power'
     */
    public void set_power(short value) {
        setUIntBEElement(offsetBits_power(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'power'
     */
    public static int size_power() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'power'
     */
    public static int sizeBits_power() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: packets
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'packets' is signed (false).
     */
    public static boolean isSigned_packets() {
        return false;
    }

    /**
     * Return whether the field 'packets' is an array (false).
     */
    public static boolean isArray_packets() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'packets'
     */
    public static int offset_packets() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'packets'
     */
    public static int offsetBits_packets() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'packets'
     */
    public int get_packets() {
        return (int)getUIntBEElement(offsetBits_packets(), 16);
    }

    /**
     * Set the value of the field 'packets'
     */
    public void set_packets(int value) {
        setUIntBEElement(offsetBits_packets(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'packets'
     */
    public static int size_packets() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'packets'
     */
    public static int sizeBits_packets() {
        return 16;
    }

}
