package rssi.message;

/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'rssi.message.RssiReportMsg'
 * rssi.message type.
 */

public class RssiReportMsg extends net.tinyos.message.Message {

    /** The default size of this rssi.message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this rssi.message. */
    public static final int AM_TYPE = 2;

    /** Create a new rssi.message.RssiReportMsg of size 4. */
    public RssiReportMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new rssi.message.RssiReportMsg of the given data_length. */
    public RssiReportMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.RssiReportMsg with the given data_length
     * and base offset.
     */
    public RssiReportMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.RssiReportMsg using the given byte array
     * as backing store.
     */
    public RssiReportMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.RssiReportMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RssiReportMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.RssiReportMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RssiReportMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.RssiReportMsg embedded in the given rssi.message
     * at the given base offset.
     */
    public RssiReportMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new rssi.message.RssiReportMsg embedded in the given rssi.message
     * at the given base offset and length.
     */
    public RssiReportMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this rssi.message. Includes the
     * rssi.message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <rssi.message.RssiReportMsg> \n";
      try {
        s += "  [nodeId=0x"+Long.toHexString(get_nodeId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssi=0x"+Long.toHexString(get_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sourceId=0x"+Long.toHexString(get_sourceId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeId
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeId' is signed (false).
     */
    public static boolean isSigned_nodeId() {
        return false;
    }

    /**
     * Return whether the field 'nodeId' is an array (false).
     */
    public static boolean isArray_nodeId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeId'
     */
    public static int offset_nodeId() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeId'
     */
    public static int offsetBits_nodeId() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'nodeId'
     */
    public short get_nodeId() {
        return (short)getUIntBEElement(offsetBits_nodeId(), 8);
    }

    /**
     * Set the value of the field 'nodeId'
     */
    public void set_nodeId(short value) {
        setUIntBEElement(offsetBits_nodeId(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeId'
     */
    public static int size_nodeId() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeId'
     */
    public static int sizeBits_nodeId() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: short, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (false).
     */
    public static boolean isSigned_rssi() {
        return false;
    }

    /**
     * Return whether the field 'rssi' is an array (false).
     */
    public static boolean isArray_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi() {
        return 8;
    }

    /**
     * Return the value (as a short) of the field 'rssi'
     */
    public short get_rssi() {
        return (short)getSIntBEElement(offsetBits_rssi(), 16);
    }

    /**
     * Set the value of the field 'rssi'
     */
    public void set_rssi(short value) {
        setSIntBEElement(offsetBits_rssi(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssi'
     */
    public static int size_rssi() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssi'
     */
    public static int sizeBits_rssi() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sourceId
    //   Field type: short, unsigned
    //   Offset (bits): 24
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sourceId' is signed (false).
     */
    public static boolean isSigned_sourceId() {
        return false;
    }

    /**
     * Return whether the field 'sourceId' is an array (false).
     */
    public static boolean isArray_sourceId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sourceId'
     */
    public static int offset_sourceId() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sourceId'
     */
    public static int offsetBits_sourceId() {
        return 24;
    }

    /**
     * Return the value (as a short) of the field 'sourceId'
     */
    public short get_sourceId() {
        return (short)getUIntBEElement(offsetBits_sourceId(), 8);
    }

    /**
     * Set the value of the field 'sourceId'
     */
    public void set_sourceId(short value) {
        setUIntBEElement(offsetBits_sourceId(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'sourceId'
     */
    public static int size_sourceId() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sourceId'
     */
    public static int sizeBits_sourceId() {
        return 8;
    }

}
